version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:mysecretpassword@db:5432/tradeflow
      SECRET_KEY: supersecretkey
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      # Validation Fields
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: tradeflow
      FINNHUB_API_KEY: "d50aak1r01qsabps6scgd50aak1r01qsabps6sd0"
    networks:
      - tradeflow-network

  db:
    image: postgres:15  # Switched from alpine to standard debian
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword  # Map syntax (Key: Value)
      POSTGRES_DB: tradeflow
    ports:
      - "5432:5432"
    networks:
      - tradeflow-network

networks:
  tradeflow-network:
    driver: bridge